"""Generate words.js and puzzles.js.

5-letter (main mode): Wordle answer list = common, Wordle allowed list = accepted guesses.
4-letter (easy mode): top-N subtitle-frequency words that are in the macOS dictionary = common,
all lowercase 4-letter dictionary words = accepted guesses.
A puzzle is scheduled only if it has at least one all-common-word solution.
"""
import json, random, datetime, os, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..') + '/'
SRC = {
    'answers.txt': 'https://gist.githubusercontent.com/cfreshman/a03ef2cba789d8cf00c08f767e0fad7b/raw/wordle-answers-alphabetical.txt',
    'allowed.txt': 'https://gist.githubusercontent.com/cfreshman/cdcdf777450c5b5301e439061d29694c/raw/wordle-allowed-guesses.txt',
    'en_50k.txt':  'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/en/en_50k.txt',
    'google10k.txt': 'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt',
}
for name, url in SRC.items():
    p = os.path.join(HERE, name)
    if not os.path.exists(p):
        urllib.request.urlretrieve(url, p)
def lines(name): return [l.split()[0] for l in open(os.path.join(HERE, name)) if l.strip()]

EPOCH = datetime.date(2026, 9, 4)
AL = 'abcdefghijklmnopqrstuvwxyz'
# Never accepted anywhere. Slurs and the like.
NEVER = set('''cunt homo dyke kike spic gook coon paki cuck fags fagg chav spaz wops whor negs nigs nazi rape'''.split())
# Not used as start words (and not in the common set), but accepted as guesses. Family game, but DUCK -> DICK -> DIRK -> DIRT is fair play.
BLOCK = NEVER | set('''shit fuck cock dick piss tits twat slut crap arse wank jizz cums anal porn jism muff poof poon smeg turd
boob boobs dong knob pube pubes sexy dead died kill hell damn nude suck scum dope puke pimp poop puss butt lust bong drug womb
wont hath kung kang ming wong chun shan
mina khan bree cass burt cain cora chad rory lucy tate hong luna mona jake paco mack nash turk wang lina yang bing yale york tory
lire dont cant baba whoo ahem gosh dang darn heck thee hers taps thou hast doth
thy ye yea nah yep yup hmm ohh ahh ummm wanna gotta lemme
mali bali sept sans para soma dell mart gage lite corp poly meta beta'''.split())
# Subtitle frequency lists are full of first names that are also lowercase dictionary words. Drop them,
# except words that are unmistakably common nouns/verbs in their own right.
NAMES_OK = set('bill rose mark june wade dawn gene mill park dale hale beck hunt hart sage dean jack ford holt grant'.split())
PROPER = {w.strip().lower() for w in open('/usr/share/dict/propernames') if w.strip()} - NAMES_OK

def solve_count(start, common, L, cap=1000):
    n = 0
    def dfs(cur, used):
        nonlocal n
        if n >= cap: return
        if sum(cur[i] != start[i] for i in range(L)) == L: n += 1; return
        for i in range(L):
            if cur[i] != start[i]: continue
            for c in AL:
                if c in start: continue
                w = cur[:i] + c + cur[i+1:]
                if w in common and w not in used:
                    used.add(w); dfs(w, used); used.discard(w)
    dfs(start, {start}); return n

def schedule(common_list, L, seed, first=None):
    common = set(common_list)
    puz = [(w, solve_count(w, common, L)) for w in common_list]
    puz = [p for p in puz if p[1] > 0]
    random.seed(seed); random.shuffle(puz)
    if first:
        puz = [p for p in puz if p[0] != first[0]]; puz.insert(0, first)
    return [[(EPOCH + datetime.timedelta(days=i)).isoformat(), w, n] for i, (w, n) in enumerate(puz)]

# ---- 5 letters ----
answers = [w for w in lines('answers.txt') if w not in BLOCK]
allowed = [w for w in lines('allowed.txt') if w not in NEVER]
sched5 = schedule(answers, 5, 20260904, first=('brace', 2))

# ---- 4 letters ----
sysdict = {w.strip() for w in open('/usr/share/dict/words') if w.strip().islower() and w.strip().isalpha()}
WEB = set(lines('google10k.txt'))   # second corpus (web text): a word must be common in both, which kills most first names
freq4 = [w for w in lines('en_50k.txt') if len(w) == 4 and w in sysdict and w in WEB and w not in BLOCK and w not in PROPER]
common4 = freq4[:1000]
allowed4 = sorted(w for w in sysdict if len(w) == 4 and w not in NEVER and w not in set(common4))
sched4 = schedule(common4, 4, 20260904)

with open(OUT + 'words.js', 'w') as f:
    f.write('// Generated by tools/gen.py. 5-letter: Wordle answer/allowed lists. 4-letter: frequency-ranked common words + macOS dictionary.\n')
    f.write('const WORDS = {\n')
    f.write('  5: { common: ' + json.dumps(answers, separators=(',', ':')) + ',\n       accepted: ' + json.dumps(allowed, separators=(',', ':')) + ' },\n')
    f.write('  4: { common: ' + json.dumps(common4, separators=(',', ':')) + ',\n       accepted: ' + json.dumps(allowed4, separators=(',', ':')) + ' },\n')
    f.write('};\n')
with open(OUT + 'puzzles.js', 'w') as f:
    f.write('// Daily schedules: [date, word, commonSolutionCount]. One puzzle per calendar day per mode from 2026-09-04.\n')
    f.write('// Every word has at least one all-common-word solution. Generated by tools/gen.py.\n')
    f.write('const SCHEDULE = {\n  5: ' + json.dumps(sched5, separators=(',', ':')) + ',\n  4: ' + json.dumps(sched4, separators=(',', ':')) + '\n};\n')
with open(os.path.join(HERE, 'schedule.txt'), 'w') as f:
    for L, sch in ((5, sched5), (4, sched4)):
        f.write(f'== {L}-letter ({len(sch)} days) ==\n')
        for i, (d, w, n) in enumerate(sch): f.write(f"#{i+1:<4} {d}  {w.upper()}  ({n}{'+' if n>=1000 else ''} solution{'s' if n!=1 else ''})\n")
print('5:', len(sched5), '4:', len(sched4), 'common4:', len(common4), 'accepted4:', len(allowed4))
