import json, random, datetime
answers = [w.strip() for w in open('answers.txt') if w.strip()]
allowed = [w.strip() for w in open('allowed.txt') if w.strip()]
A = set(answers)

def solve(start, vocab):
    S = set(start); sols = []
    def dfs(word, touched, path):
        if len(path) == 5: sols.append(list(path)); return
        for i in range(5):
            if i in touched: continue
            for c in 'abcdefghijklmnopqrstuvwxyz':
                if c in S: continue
                w = word[:i]+c+word[i+1:]
                if w in vocab and w not in path:
                    path.append(w); dfs(w, touched|{i}, path); path.pop()
    dfs(start, frozenset(), []); return sols

puz = []
for s in answers:
    n = len(solve(s, A))
    if n: puz.append((s, n))
random.seed(20260904)
random.shuffle(puz)
puz.remove(('brace', 2)); puz.insert(0, ('brace', 2))
out = '/Users/cmanna/Ribbescobb-Labs/Unwordle/'
with open(out+'words.js','w') as f:
    f.write('// Wordle answer list (common words) and allowed-guess list. Generated by tools/gen.py.\n')
    f.write('const ANSWERS = ' + json.dumps(answers, separators=(',',':')) + ';\n')
    f.write('const ALLOWED = ' + json.dumps(allowed, separators=(',',':')) + ';\n')
d0 = datetime.date(2026, 9, 4)
sched = [[(d0 + datetime.timedelta(days=i)).isoformat(), w, n] for i, (w, n) in enumerate(puz)]
with open(out+'puzzles.js','w') as f:
    f.write('// Daily schedule: [date, word, commonSolutionCount]. One puzzle per calendar day, #1 = BRACE on 2026-09-04.\n')
    f.write('// Every word has at least one all-common-word solution. Generated by tools/gen.py.\n')
    f.write('const SCHEDULE = ' + json.dumps(sched, separators=(',',':')) + ';\n')
with open(out+'tools/schedule.txt','w') as f:
    for i, (d, w, n) in enumerate(sched): f.write(f"#{i+1:<4} {d}  {w.upper()}  ({n} solution{'s' if n!=1 else ''})\n")
print(len(puz), puz[:6])
